export interface ClientDto
{
  id: string,
  name: string, 
  email: string,
  phone: string,
  dob: Date,
  status: string,
  service: number,
  serviceName: string,

  usernane: string,
  password: string,
  isAutogenerated: boolean,

  address: string,
  university: string,
  course: string,
  courseYear: string,


}
