trigger:
- prod

pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'angular-cli'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'ng build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run ng build --prod'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: dist

